### ISSUE TITLE
Bug in User Feature

### ISSUE THREAD

**Issue by quangn2212** [dinhlockt02/cs_chat_app_server#15]
- Get User: need to return "update_profile" and "email_verified".
- Update User: 
<img width="903" alt="Screenshot 2023-06-22 at 23 41 49" src="https://github.com/dinhlockt02/cs_chat_app_server/assets/91067905/bcc313e5-178d-4ea3-9c0a-fd6b4f317310">
<img width="947" alt="Screenshot 2023-06-22 at 23 42 09" src="https://github.com/dinhlockt02/cs_chat_app_server/assets/91067905/9ee79eae-e3ea-4338-825a-db997f6838da">

**Comment by dinhlockt02** [comment]
You should try to send null value (or not send) the field that you do not want to update @quangnhat22. e.g.
```json
{
   "name": "updated name"
}
```
this should update only name, others should be omitted
