### ISSUE TITLE
Need to feature can show all chatrooms of user

### ISSUE THREAD

**Issue by quangn2212** [dinhlockt02/cs_chat_app_server#2]

**Comment by dinhlockt02** [comment]
![telegram-cloud-photo-size-5-6060005031828110583-y](https://github.com/dinhlockt02/cs_chat_app_server/assets/20945393/6351f08b-075f-4fa7-b704-4a3235741de4)
![telegram-cloud-photo-size-5-6060005031828110590-y](https://github.com/dinhlockt02/cs_chat_app_server/assets/20945393/5570d748-f5a0-4449-86e5-f19ec86e4c1d)
