### ISSUE TITLE
Need to add type field in notification

### ISSUE THREAD

**Issue by quangn2212** [dinhlockt02/cs_chat_app_server#9]
Support Type

**Comment by dinhlockt02** [comment]
Need you guy to list all type of notification needed @quangnhat22

**Comment by dinhlockt02** [comment]
Please check a field named action in the notification `payload`
I'll keep a reference [Notification Type](https://github.com/dinhlockt02/cs_chat_app_server/blob/master/api-docs/notification_type.md)
